# Basic Site Settings
locale: "en-US"
title: "Kwang Hyun Kim | REACT"
title_separator: "-"
name: &name "Kwang Hyun Kim"
description: &description "Ph.D. Candidate in Zeolite Engineering at UNIST"
url: "https://kwanghyunkim-react.github.io"
baseurl: ""
repository: "KwangHyunKim-REACT/KwangHyunKim-REACT.github.io"

include:
  - _pages

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Site Author
author:
  avatar: "profile.png"
  name: "Kwang Hyun Kim"
  pronouns: "He/Him"
  bio: "Rational Engineering of Active Catalytic Topologies (REACT)"
  location: "Ulsan, South Korea"
  employer: "UNIST"
  email: "rhkdgus131@unist.ac.kr"
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid: "https://orcid.org/0009-0003-0532-2711"
  github: "KwangHyunKim-REACT"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
